# Generated by Django 6.0.6 on 2026-06-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('manual', 'User Posted'), ('dubizzle', 'Dubizzle'), ('aqarmap', 'Aqarmap'), ('facebook', 'Facebook Marketplace')], default='manual', max_length=20)),
                ('source_url', models.URLField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='listing_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
    ]
